### PR TITLE
docs: update codeblocks in livepeer studio docs to reflect sdk documentation

### LINKED ISSUE #245: Update codeblocks in Livepeer Studio docs to reflect SDK documentation
Currently, the path between the docs and the SDK is not clear -- it's mentioned in a few places, but there's no clear point of handoff. To reduce this confusion (and prevent users from having to review two sets of docs) we should update the code blocks to include livepeerjs, fetch and curl. 

There are some places where there isn't livepeerjs code that is applicable, and in those places we should keep the existing javascript code. Ex. list all assets.

### PR DESCRIPTION
**Pull request by ichung08**
resolves #245 

Changes
- Added Livepeerjs code example to `Get Viewer Engagement`, `Upload Video Asset`, `Update Video Asset`, and `Upload Asset to IPFS`
- removed curl blocks

### CODE REVIEW

**Comment by ichung08** [comment]
remove `curl` code blocks

**Comment by adamsoffer** [comment]
@ichung08 let's make sure all guides are updated. Notice the update guide wasn't updated.

CleanShot 2022-11-06 at 10 32 28@2x

**Review by adamsoffer — CHANGES_REQUESTED** [review]
@ichung08 let's make sure all guides are updated. Noticed the update guide wasn't updated.

CleanShot 2022-11-06 at 10 32 28@2x

**Comment by adamsoffer** [comment]
Let's rename `Livepeer.js` and `Fetch`.

CleanShot 2022-11-14 at 12 07 10@2x

**Pull request closed without merging**
